### PR TITLE
Add SFTP support

### PR DESCRIPTION
**Pull request by AndroMaster436**

### CODE REVIEW

**Review by RohitKushvaha01 — APPROVED** [review]

**Comment by AndroMaster436** [comment]
@RohitKushvaha01 plz help me with method openFolder in SFTPFilesystem

```kotlin
fun openFolder(remotePath: String) {
        if (channel == null || !channel!!.isConnected) {
            rkUtils.toast("Error. Not connected!")
            return
        }
        val tempDir = File(context.filesDir, connectionString).apply {
            if (!exists()) {
                mkdirs()
            }
        }
        try {
            val files = channel?.ls(remotePath) as? List<ChannelSftp.LsEntry>
            files?.forEach { entry ->
                val remoteFilePath = "$remotePath/${entry.filename}"
                val localFile = File(tempDir, entry.filename)
                if (!localFile.exists()) {
                    if (entry.attrs.isDir) {
                        localFile.mkdirs()
                    } else {
                        localFile.createNewFile()
                    }
                }
            }
        } catch (e: Exception) {
            rkUtils.toast("${remotePath} not found")
        }
    }
```

It's very buggy load folders in root folder

**Comment by AndroMaster436** [comment]
> @RohitKushvaha01 plz help me with method openFolder in SFTPFilesystem
> 
> ```kotlin
> fun openFolder(remotePath: String) {
>         if (channel == null || !channel!!.isConnected) {
>             rkUtils.toast("Error. Not connected!")
>             return
>         }
>         val tempDir = File(context.filesDir, connectionString).apply {
>             if (!exists()) {
>                 mkdirs()
>             }
>         }
>         try {
>             val files = channel?.ls(remotePath) as? List<ChannelSftp.LsEntry>
>             files?.forEach { entry ->
>                 val remoteFilePath = "$remotePath/${entry.filename}"
>                 val localFile = File(tempDir, entry.filename)
>                 if (!localFile.exists()) {
>                     if (entry.attrs.isDir) {
>                         localFile.mkdirs()
>                     } else {
>                         localFile.createNewFile()
>                     }
>                 }
>             }
>         } catch (e: Exception) {
>             rkUtils.toast("${remotePath} not found")
>         }
>     }
> ```
> 
> It's very buggy load folders in root folder

Example:
/root - load successfully
/root/folder - empty folder

**Comment by AndroMaster436** [comment]
Maybe I found reason

**Comment by RohitKushvaha01** [comment]
> @RohitKushvaha01 plz help me with method openFolder in SFTPFilesystem
> 
> ```kotlin
> fun openFolder(remotePath: String) {
>         if (channel == null || !channel!!.isConnected) {
>             rkUtils.toast("Error. Not connected!")
>             return
>         }
>         val tempDir = File(context.filesDir, connectionString).apply {
>             if (!exists()) {
>                 mkdirs()
>             }
>         }
>         try {
>             val files = channel?.ls(remotePath) as? List<ChannelSftp.LsEntry>
>             files?.forEach { entry ->
>                 val remoteFilePath = "$remotePath/${entry.filename}"
>                 val localFile = File(tempDir, entry.filename)
>                 if (!localFile.exists()) {
>                     if (entry.attrs.isDir) {
>                         localFile.mkdirs()
>                     } else {
>                         localFile.createNewFile()
>                     }
>                 }
>             }
>         } catch (e: Exception) {
>             rkUtils.toast("${remotePath} not found")
>         }
>     }
> ```
> 
> It's very buggy load folders in root folder

I am busy right now, I'll check it after 2pm (IST)

**Comment by AndroMaster436** [comment]
> > @RohitKushvaha01 plz help me with method openFolder in SFTPFilesystem
> > ```kotlin
> > fun openFolder(remotePath: String) {
> >         if (channel == null || !channel!!.isConnected) {
> >             rkUtils.toast("Error. Not connected!")
> >             return
> >         }
> >         val tempDir = File(context.filesDir, connectionString).apply {
> >             if (!exists()) {
> >                 mkdirs()
> >             }
> >         }
> >         try {
> >             val files = channel?.ls(remotePath) as? List<ChannelSftp.LsEntry>
> >             files?.forEach { entry ->
> >                 val remoteFilePath = "$remotePath/${entry.filename}"
> >                 val localFile = File(tempDir, entry.filename)
> >                 if (!localFile.exists()) {
> >                     if (entry.attrs.isDir) {
> >                         localFile.mkdirs()
> >                     } else {
> >                         localFile.createNewFile()
> >                     }
> >                 }
> >             }
> >         } catch (e: Exception) {
> >             rkUtils.toast("${remotePath} not found")
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's very buggy load folders in root folder
> 
> I am busy right now, I'll check it after 2pm (IST)

Ok

**Comment by AndroMaster436** [comment]
Updated code

```kotlin
fun openFolder(remotePath: String) {
        if (channel == null || !channel!!.isConnected) {
            rkUtils.toast("Error. Not connected!")
            return
        }
        val tempDir = File(context.filesDir, connectionString + remotePath).apply {
            if (!exists()) {
                mkdirs()
            }
        }
        try {
            val files = channel?.ls(remotePath) as? List<ChannelSftp.LsEntry>
            files?.forEach { entry ->
                val localFile = File(tempDir, entry.filename)
                if (!localFile.exists()) {
                    if (entry.attrs.isDir) {
                        localFile.mkdirs()
                    } else {
                        localFile.createNewFile()
                    }
                }
            }
        } catch (e: Exception) {
            rkUtils.toast("${remotePath} not found")
        }
    }
```

**Pull request closed without merging**
